### ISSUE TITLE
Objeto com controle de Inserção, Alteração, Exclusão

### ISSUE THREAD

**Issue by adrbarros** [carlosast/Speed-ORM#1]
Muito Show o Speed-ORM, estou utilizando com um novo projeto e está indo 100% e muito rápido os retornos.

Uma duvida, sobre uma funcionalidade (Já vi isso em um ORM Prório, de Uma Empresa de Desenvolvimento), se existe isso dentro de seu projeto

Imagine o conceito de mestre-detalhe

Pedido
PedidoItens

Tipo:
Se o Objeto sofreu alteração executa o Update
Se o Objeto foi inserido executa o Insert
Se foi excluido o Delete

Assim nos meus itens (Total de 5 itens), no momento em que estou fazendo uma Alteração
Altero o item 1          (Update)
Excluo o item 4 e 5    (Delete)
Incluo mais 2 itens    (Insert)
Os itens 2 e 3 (Não iriam ter nenhum ação enviadas ao banco de dados, pq não sofreram nenhuma alteração)

Outro exemplo é um cadastro simples: Uma Pessoa
Recupero os Dados de uma pessoa, e sem alterar nada no Objeto, mando fazer um Update, essa ação não seria enviada ao Banco de Dados, pois o Objeto Pessoa não sofreu nenhuma alteração.

Chequei a tentar realizar essa implementação em um modelo meu, mas o consumo de memoria para esses procedimentos são altos, um dos principais motivos são os caches de properties alteradas que guardam os valores anteriores ao Set na Property

**Comment by carlosast** [comment]
Olá Adriano,

	Obrigado pelo retorno. Realmente o Speed foi pensado, desde o início, pra ser rápido. Fico contente que tenha gostado.

Quanto à sua dúvida: "Uma duvida, sobre uma funcionalidade (Já vi isso em um ORM Próprio, de Uma Empresa de Desenvolvimento), se existe isso dentro de seu projeto ...",

o Speed não possui esse recurso. Para fazer isso ele teria que fazer um proxy pra manter os valores anteriores ou usar um flag mas para isso teria que usar um proxy tb. Pra manter o Speed o mais rápido possível tive que sacrificar recursos pela performance.
O que o Speed tem é o seguinte:

Toda classe do Speed herda da classe Record. A classe record possui a propriedade RecordStatus que possui os seguintes valores:
       RecordStatus.New (quando uma instância é criada;
       RecordStatus.Existing (quando um registro é lida da base de dados usado o método Select, SelectPage (esse método faz paginação automática, é muito útil) ou o SelectSql (esse método permite vc passar todos o sql);
       RecordStatus.Deleted: esse valor deve ser setado pelo programador.
Tendo isso em mente, vc pode chamar o método Save que fará o Insert, Update ou Delete baseado nos valores de RecodStatus
    O método Save tem a seguinte lógica:

if (value.RecordStatus == RecordStatus.Existing)
    return Update(db, value);
else if (value.RecordStatus == RecordStatus.New)
    return Insert(db, value);
else // if (value.RecordStatus == RecordStatus.Deleted)
    return Delete(db, value);

**Comment by carlosast** [comment]
Esqueci de mencionar. o Speed cria para classe gerada, o método IsEqual.
Com essa chamada vc pode verificar se teve alteração na classe.
Ex: 
var cli = new Cliente();
var cli2 = new Cliente();
.......
if (cli1.IsEqual(cli2))
{
.....
}
